[package]
edition = "2021"
name = "forest-flame-student-tests"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dev-dependencies]
prettydiff = "0.6.4"
